name: check branch up to date

on:
  workflow_call:
    inputs:
      required_branch:
        description: 배포시 필수적으로 포함해야 할 브랜치 이름
        required: true
        type: string
      check_branch:
        description: 검증이 필요한 브랜치 이름
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: croquiscom/github-actions/check-branch-up-to-date@main
        with:
          required_branch: ${{ inputs.required_branch }}
          check_branch: ${{ inputs.check_branch }}
