name: deploy to ecs

on:
  workflow_call:
    inputs:
      deployment_uuid:
        description: 배포 UUID
        default: ''
        type: string
      release_message:
        description: 릴리즈 메시지
        default: ''
        type: string
      image:
        description: 배포할 이미지
        required: true
        type: string
      user_name:
        description: 배포한 사용자
        required: false
        type: string
      stage:
        description: 스테이지
        type: string
      cluster_name:
        description: 클러스터 이름
        required: true
        type: string
      service_name:
        description: 서비스 이름
        required: true
        type: string
      task_definition_name:
        description: 태스크 정의 파일 이름
        required: true
        type: string
      branch:
        description: 브랜치
        type: string
      git_ref:
        description: 커밋
        type: string
      slack_notify_channel:
        description: 슬랙 알림 채널
        required: true
        type: string
      slack_thread_key:
        description: 슬랙 메시지 갱신을 위한 키
        type: string
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_KEY:
        required: true
      RECORD_DEPLOYMENT_STEP_URL:
        required: true
      RECORD_DEPLOYMENT_STEP_TOKEN:
        required: true

jobs:
  deploy:
    name: deploy ${{ inputs.branch }} to ${{ inputs.stage }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Deploy
        uses: croquiscom/github-actions/deploy-ecs@main
        with:
          deployment_uuid: ${{ inputs.deployment_uuid }}
          release_message: ${{ inputs.release_message }}
          image: ${{ inputs.image }}
          user_name: ${{ inputs.user_name }}
          stage: ${{ inputs.stage }}
          cluster_name: ${{ inputs.cluster_name }}
          service_name: ${{ inputs.service_name }}
          task_definition_name: ${{ inputs.task_definition_name }}
          branch: ${{ inputs.branch }}
          git_ref: ${{ inputs.git_ref }}
          slack_notify_channel: ${{ inputs.slack_notify_channel }}
          slack_thread_key: ${{ inputs.slack_thread_key }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          RECORD_DEPLOYMENT_STEP_URL: ${{ secrets.RECORD_DEPLOYMENT_STEP_URL }}
          RECORD_DEPLOYMENT_STEP_TOKEN: ${{ secrets.RECORD_DEPLOYMENT_STEP_TOKEN }}
