name: deploy to eks

on:
  workflow_call:
    inputs:
      deployment_uuid:
        description: 배포 UUID
        default: ''
        type: string
      release_message:
        description: 릴리즈 메시지
        default: ''
        type: string
      image_tag:
        description: 배포할 이미지
        required: true
        type: string
      stage:
        description: 스테이지
        type: string
      service_name:
        description: 서비스 이름
        required: true
        type: string
      branch:
        description: 브랜치
        type: string
      git_ref:
        description: 커밋
        type: string
      slack_notify_channel:
        description: 슬랙 알림 채널
        required: true
        type: string
      slack_thread_key:
        description: 슬랙 메시지 갱신을 위한 키
        type: string
    secrets:
      GITHUB_BOT_TOKEN:
        required: true
      RECORD_DEPLOYMENT_STEP_URL:
        required: true
      RECORD_DEPLOYMENT_STEP_TOKEN:
        required: true

jobs:
  deploy:
    name: deploy ${{ inputs.branch }} to ${{ inputs.stage }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Deploy
        uses: croquiscom/github-actions/deploy-eks@main
        with:
          deployment_uuid: ${{ inputs.deployment_uuid }}
          release_message: ${{ inputs.release_message }}
          image_tag: ${{ inputs.image_tag }}
          stage: ${{ inputs.stage }}
          service_name: ${{ inputs.service_name }}
          branch: ${{ inputs.branch }}
          git_ref: ${{ inputs.git_ref }}
          slack_notify_channel: ${{ inputs.slack_notify_channel }}
          slack_thread_key: ${{ inputs.slack_thread_key }}
          GITHUB_BOT_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
          RECORD_DEPLOYMENT_STEP_URL: ${{ secrets.RECORD_DEPLOYMENT_STEP_URL }}
          RECORD_DEPLOYMENT_STEP_TOKEN: ${{ secrets.RECORD_DEPLOYMENT_STEP_TOKEN }}
